### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by dayofdoom** [mingzejin11/GanJing-keyboard#2]
Hello,

I've been trying to get my GanJing65 to work. I've checked all the component placements and solder joints, they appear to be without issue. The power LED lights up when plugged in. I can't get the board to be visable however - see the output from QMK toolbox. 
```
    avrdude: warning: cannot set sck period. please check for usbasp firmware update.
    avrdude: error: program enable: target doesn't answer. 1 
    avrdude: initialization failed, rc=-1
             Double check connections and try again, or use -F to override
             this check.
    
    
    avrdude done.  Thank you.
```

Part of my troubleshooting has been using my [LCK75](https://github.com/lyso1/LCK75) to flash the MCU since I wasn't able to with the GanJing65. I was able to successfully burn the bootloader and flash the GanJing firmware, so I know the chip is good. The computer recognized the board after flashing too. 

After flashing the chip, I put it back into the GanJing but it still won't show up. It feels like there is a short somewhere or something but I've hit my skill wall and I'm not sure where to go from here. Do you have any suggestions?

**Comment by mingzejin11** [comment]
First of all, lemme just start by saying I really appreciate your interest in my project! You're the first person I'm aware of who's trying to actually build it besides myself.

Onto your question, I'll be completely transparent, I ran into the same wall that you're running into right now with programming. That's why I don't have a prototype on video, I wasn't able to flash my microcontroller for the same reasons. I'm currently working on a second revision of the GanJing 65 (although I might rename it to the GanJing 70 because of the different layout), you can find it on my GitHub and it uses far fewer components and relies on the Elite-c for the MCU. I'm currently working on it right now and have a working prototype, but I'm still in 3rd-year electrical engineering so I haven't found the time to prototype the case quite yet, after this week's assignments and labs are done, I'll be laser cutting the case. 

The GanJing 70 is designed to actually be gasket mounted and has a larger OLED with a Pikachu animation on it that I made(I figured the Bongo Cat one was a little overused).

Okay, I'm realizing now that I actually didn't help you at ALL with this response haha. Try checking out the bootloader stuff for the Discipline board, these two boards should use the same bootloader. That's the only real suggestion I have. I'm so sorry I can't be more help, but I promise the GanJing 70 is much easier to assemble and work with if you're up for that challenge :)

**Comment by dayofdoom** [comment]
I'm going to try the make the ganjing v2, thats for sure. Looks very cool. I'm commited to getting this v1 to work too. I got the bootloader on the MCU using a different PCB (non GanJing), so I know the bootloader works ok. What I've noticed is that no matter what, when the MCU is in the GanJing, it can't be seen by the computer. The reset and boot buttons don't work either. In theory, pressing the boot button should reboot the board but the LED doesn't cycle when boot is pressed. My gut tells me something needs to jumpered from A to B to fix a missing connection but I'm a hobbyist, not an EE. Any thoughts?

**Comment by dayofdoom** [comment]
I think the OLED pinout is reversed? See the sample image below? I think this explains why the LED was getting power but the OLED wasn't. Could this impact anything else?
<img width="1815" alt="Screen Shot 2022-01-26 at 2 53 53 PM" src="https://user-images.githubusercontent.com/14165909/151260733-6a6c23f1-7460-4780-82b9-cd051a2f5391.png">
<img width="417" alt="Screen Shot 2022-01-26 at 2 56 20 PM" src="https://user-images.githubusercontent.com/14165909/151260990-b943331d-0ae0-4097-abab-43f626e32bce.png">

**Comment by dayofdoom** [comment]
Following up on this - I'm still not able to get the board to flash successfully BUT I've been able to flash the MCU in a different board and then get the GanJing65 to work. So, progress :) I'm going to close this because you've already moved on to v2.
